// Regression coverage for the current local search; Google Places was removed.
const assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{const server=http.createServer((req,res)=>{const file=path.resolve(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/+/, '')||'index.html');if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;let browser;
try{browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'});
for(const width of [390,820,1366])for(const theme of ['light','dark']){const context=await browser.newContext({viewport:{width,height:900},geolocation:{latitude:31.518,longitude:74.262},permissions:['geolocation']});const errors=[],requests=[];await context.route('**/*',r=>{requests.push(r.request().url());return r.request().url().startsWith(base)?r.continue():r.fulfill({contentType:r.request().resourceType()==='stylesheet'?'text/css':'text/javascript',body:''});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(base);await page.addStyleTag({content:'*{animation-duration:0s!important;transition-duration:0s!important;scroll-behavior:auto!important}'});await page.evaluate(t=>applyTheme(t),theme);
assert.ok(await page.locator('#page-home').isVisible());await page.locator('#main-location-input').fill('MAO');await page.locator('#stop-search-suggestions [data-stop-key]').first().click();assert.ok(await page.locator('#page-result').isVisible());assert.ok((await page.locator('#result-content-container').innerText()).includes('MAO College'));
await page.locator('.brand-logo').click();await page.locator('#main-location-input').press('Escape');await page.locator('#btn-locate-me').click();await page.waitForFunction(()=>appState.currentLocation?.source==='gps'&&appState.activePage==='result');const gps=await page.evaluate(()=>({actual:appState.recommendationResults.matchingRoutes.map(i=>[i.route.id,i.stopIndex]),expected:findNearbyRoutes(appState.currentLocation.lat,appState.currentLocation.lng,appState.selectedCampus).matchingRoutes.map(i=>[i.route.id,i.stopIndex])}));assert.deepEqual(gps.actual,gps.expected);await page.waitForFunction(()=>!document.querySelector('#search-loading-overlay').classList.contains('active'));
if(width<=1024){await page.locator('.nav-toggle').click();await page.locator('.mobile-menu-item[data-page="routes"]').click();assert.equal(await page.locator('.nav-toggle').getAttribute('aria-expanded'),'false');}else await page.locator('.nav-btn[data-page="routes"]').click();
for(const campus of ['main','ksk']){await page.locator('#route-schedule-search').fill('');await page.locator('#page-routes .route-campus-btn[data-campus="'+campus+'"]').click();for(const query of ['19','Route 19','MAO','Islam','Local Government','  local   GOVERNMENT  ','Ismailpura',campus,'zzzz-no-route']){await page.locator('#route-schedule-search').fill(query);const expected=await page.evaluate(({campus,query})=>UET_DATA.routes.filter(r=>r.campusId===campus&&routeMatchesScheduleSearch(r,query)).map(r=>'route-card-'+r.id),{campus,query});const actual=await page.locator('#routes-detail-container .route-card').evaluateAll(es=>es.map(e=>e.id));assert.deepEqual(actual,expected);if(!actual.length)assert.ok(await page.getByText('No matching routes found',{exact:true}).isVisible());if(campus==='main'&&['19','Route 19','Islam','Local Government','  local   GOVERNMENT  ','Ismailpura'].includes(query))assert.ok(actual.length>0,query);}}
await page.locator('#route-schedule-search').fill('');const card=page.locator('#routes-detail-container .route-card').first();await card.getByRole('button',{name:'View Full Route'}).click();assert.equal(await page.locator('#routes-detail-container .route-card').count(),0);const detailHash=new URL(page.url()).hash;await page.getByRole('button',{name:'Save Route',exact:true}).click();await page.evaluate(()=>navigateToPage('favorites'));assert.ok(await page.locator('#page-favorites .route-card').count()>0);await page.locator('#page-favorites').getByRole('button',{name:'View Route',exact:true}).first().click();assert.equal(new URL(page.url()).hash,detailHash);await page.getByRole('button',{name:'Print / Download',exact:true}).click();await page.keyboard.press('Escape');await page.locator('.route-back-button').click();assert.ok(await page.locator('#route-schedule-controls').isVisible());await page.locator('#routes-detail-container .route-card').first().getByRole('button',{name:'View Full Route'}).click();await page.goBack();await page.locator('#route-schedule-controls').waitFor();await page.goForward();await page.locator('.route-detail-heading').waitFor();await page.reload();await page.locator('.route-detail-heading').waitFor();
assert.ok(!requests.some(u=>/maps\.googleapis|js\/config\.js/.test(u)));assert.deepEqual(errors,[]);console.log(`PASS ${width}px ${theme}: local search, GPS parity, campus-filtered schedule queries, drawer, full route/history, saved routes, print, console clean`);await context.close();}
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
